### ISSUE TITLE
Please add the racket topic to this repo

### ISSUE THREAD

**Issue by spdegabrielle** [DexterLagan/lsh#1]
Hi ,
Please add the racket topic to this repo - I think others will be interested and this will help them find it at https://github.com/topics/racket

https://help.github.com/en/articles/classifying-your-repository-with-topics

Kind regards,

Stephen

**Comment by DexterLagan** [comment]
Hi Stephen,

  Somehow I never noticed this issue! I feel horrible. I added the topic to all my racket repos. Thanks for letting me know.

Dex

**Comment by spdegabrielle** [comment]
My apologies - I didn't intend to make you feel bad. 
Thank you.
